- name: Create the ansible user account
  ansible.builtin.user:
    name: "{{ ansible_user_name }}"
    password: "{{ ansible_user_password | password_hash('sha512') }}"
    groups: sudo
    append: true
    shell: /bin/bash
    create_home: true
    state: present

- name: Add SSH public key for passwordless login
  ansible.posix.authorized_key:
    user: "{{ ansible_user_name }}"
    key: "{{ ansible_user_ssh_public_key }}"
    state: present
